hospedes/urls.py
from django.conf.urls import url
from views import HospedeList, HospedeList_All, HospedeList_Inactive, HospedeCreate, HospedeDetail, HospedeUpdate, hospedes_delete

urlpatterns = [
    url(r'^$', HospedeList.as_view(), name='list'),
    url(r'^todos/$', HospedeList_All.as_view(), name='list_all'),
    url(r'^desativados/$', HospedeList_Inactive.as_view(), name='list_des'),
    url(r'^criar/$', HospedeCreate.as_view(), name='create'),
    url(r'^detalhe/(?P<pk>[\w-]+)$', HospedeDetail.as_view(), name='detail'),
    url(r'^editar/(?P<pk>[\w-]+)$', HospedeUpdate.as_view(), name='update'),
    url(r'^remover/(?P<pk>[\w-]+)$', hospedes_delete, name='delete'),
]

pensis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^quartos/', include('quartos.urls', namespace='quartos')),
    url(r'^hospedes/', include('hospedes.urls', namespace='hospedes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    #url(r'^login', login_view, name='login'),
    #url(r'^register', register_view, name='register'),
    #url(r'^logout/', logout_view, name='logout'),

quartos/urls.py
from django.conf.urls import url
from views import quartos_list, quartos_create, quartos_delete, quartos_update


# urlpatterns = [
#     url(r'^$', posts_list, name='list'),
#     url(r'^create/$', posts_create, name='create'),
#     url(r'^(?P<slug>[\w-]+)/$', posts_detail, name='detail'),
#     url(r'^(?P<slug>[\w-]+)/edit/$', posts_update, name='update'),
#     url(r'^delete/$', posts_delete, name='delete'),
# ]

urlpatterns = [
    url(r'^$', quartos_list, name='list'),
    url(r'^criar/$', quartos_create, name='create'),
    url(r'^(?P<numero>[\w-]+)/remover/$', quartos_delete, name='delete'),
    url(r'^(?P<numero>[\w-]+)/editar/$', quartos_update, name='update'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %} Pensis {% endblock head_title %}</title>
    {% block extra_head %} {% endblock extra_head %}
</head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    {% block style %}
    {% endblock style %}
</style>

<body>
{% include 'messages.html' %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% block content %}{% endblock content %}
        </div>
    </div>
</div>


<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{% block javascript %}{% endblock javascript %}
</body>
</html>

templates/hospede_create_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{block.super}} | Quartos
{% endblock head_title %}


{% block content %}
<h1>Editar Hóspede</h1>
<div class="row">
    <div class="col-4">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary" type="submit" value="Salvar">
            <a class="btn btn-success" href="{% url 'quartos:create' %}" role="button">Salvar e Novo</a>
            <a class="btn btn-danger" href="{% url 'quartos:list' %}" role="button">Cancelar</a>
        </form>
    </div>
</div>

{% endblock content %}

templates/hospedes_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{block.super}} | Quartos
{% endblock head_title %}


{% block content %}
<h1>Novo Hóspede</h1>
<div class="row">
    <div class="col-4">
        {{object.nome}}
    </div>
</div>

{% endblock content %}

templates/hospedes_list.html
{% extends 'base.html' %}
{% block head_title %}
    {{block.super}} | Quartos
{% endblock head_title %}


{% block content %}
<h1>Lista de Hóspedes</h1>
<div class="row">
    <div class="col-12">
        <a class="btn btn-success btn-sm" href="{% url 'hospedes:create' %}" role="button">Novo Hóspede</a>
        <a class="btn btn-primary btn-sm" href="{% url 'hospedes:list_all' %}" role="button">Mostrar Todos</a>
        <a class="btn btn-primary btn-sm" href="{% url 'hospedes:list' %}" role="button">Somente Ativos</a>
        <a class="btn btn-danger btn-sm" href="{% url 'hospedes:list_des' %}" role="button">Inativos</a>
        <br>
        <br>
        <table class="table table-sm table-hover table-bordered text-center">
          <thead>
            <tr class="table-success">
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">User</th>
                <th scope="col">Cadastrado</th>
                <th scope="col">Ações</th>
            </tr>
          </thead>
            <tbody>
        {% for hospede in hospede_list %}
                <tr>
                    <th scope="row">{{hospede}}</th>
                    <td>{{hospede.email}}</td>
                    <td>{{hospede.user}}</td>
                    <td>{{hospede.created | date:"d M, Y"}}</td>
                    <td>
                        <a class="btn btn-success btn-sm" href="{% url 'hospedes:detail' pk=hospede.id %}" role="button">Ver</a>
                        <a class="btn btn-warning btn-sm" href="{% url 'hospedes:update' pk=hospede.id %}" role="button">Editar</a>
                        {% if not hospede.has_hospeddagem %}
                            {% with object=hospede.id %}
                                <button type="button" onclick="deleteModal({{hospede.id}})" class="btn btn-danger btn-sm">Remover</button>
                            {% endwith %}
                        {% endif %}
                        <input type="hidden" id="delete-{{hospede.id}}" value="{% url 'hospedes:delete' pk=hospede.id %}">
                    </td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<!-- Modal content-->
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Remover</h4>
                <button type="button" class="close" data-dismiss="modal"><span>×</span></button>

            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-danger" id="btn-confirm-delete" href="#" role="button">Sim, Remover</a>
                <button type="button"  class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block javascript %}
    <script type="text/javascript">
    function deleteModal(id){
        var deleteUrl = "http://127.0.0.1:8000/hospedes/remover/"+id
        console.log(deleteUrl);
        $("#btn-confirm-delete")[0].href = deleteUrl;
        console.log($("#btn-confirm-delete"))
        $("#deleteModal").modal();
    };
    </script>

{% endblock javascript %}

templates/messages.html
<div class="messages">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

templates/quartos_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{block.super}} | Quartos
{% endblock head_title %}


{% block content %}
<h1>Novo quarto</h1>
<div class="row">
    <div class="col-4">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary" type="submit" value="Salvar">
            <a class="btn btn-success" href="{% url 'quartos:create' %}" role="button">Salvar e Novo</a>
            <a class="btn btn-danger" href="{% url 'quartos:list' %}" role="button">Cancelar</a>
        </form>
    </div>
</div>

{% endblock content %}

templates/quartos_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/quartos_list.html
{% extends 'base.html' %}
{% block head_title %}
    {{block.super}} | Quartos
{% endblock head_title %}


{% block content %}
<h1>Lista de Quartos</h1>
<div class="row">
    <div class="col-8">
        <a class="btn btn-primary btn-sm" href="{% url 'quartos:create' %}" role="button">Novo Quarto</a>
        <br>
        <br>
        <table class="table table-sm table-hover table-bordered text-center">
          <thead>
            <tr class="table-success">
              <th scope="col">Quarto</th>
              <th scope="col">Banheiro</th>
              <th scope="col">Observação</th>
              <th scope="col">Ações</th>
            </tr>
          </thead>
            <tbody>
        {% for quarto in queryset %}
                <tr>
                    <th scope="row">{{quarto}}</th>
                    <td>{{quarto.get_banheiro}}</td>
                    <td>{{quarto.get_descricao}}</td>
                    <td><a class="btn btn-warning btn-sm" href="{% url 'quartos:update' numero=quarto.numero %}" role="button">Editar</a> {% if not quarto.has_hospede %}<a class="btn btn-danger btn-sm" href="{% url 'quartos:delete' numero=quarto.numero %}" role="button">Remover</a>{% endif %}</td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}